# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'Release notify to Ding Talk'
description: 'Notify to Ding Talk while release published, using GitHub actions.'
author: 'visiky'

branding:
  # https://actions-cool.github.io/github-action-branding/
  icon: 'file'
  color: 'blue'

inputs:
  GITHUB_TOKEN:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: true

  DING_TALK_TOKEN:
    description: 'dingtalk web hook token'
    required: true

  repo_url:
    description: 'github pull request url'

  content:
    description: 'message content'

  at_all:
    description: 'at all users'

#outputs:
#  result:
#    description: action result

runs:
  using: 'node12'
  main: 'dist/index.js'
