name: DingTalk Release Notify

on:
  release:
    types: # This configuration does not affect the page_build event above
      - published

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: install
        run: yarn install
      
      - name: format-check
        run: yarn format-check

      - name: package
        run: yarn package

  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Ding Talk Release Notify
        uses: lijinke666/ding-talk-pr-notify@main
        with:
          ding_talk_token: ${{ secrets.DING_TALK_ACCESS_TOKEN}}
          at_all: false
