name: DingTalk Release Notify

on:
  release:
    types: [published]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: install
        run: yarn install
      
      - name: format
        run: yarn format

      - name: package
        run: yarn package

      - name: DingTalk Release Nofity
      - uses: ./
        with:
          DING_TALK_TOKEN: ${{ secrets.DING_TALK_ACCESS_TOKEN}}
          at_all: false